### ISSUE TITLE
As a CIF user, I want to be able to select a "Summary Report" reporting requirement type, so that I can track it for IA projects

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#926] opened 2022-08-04 18:50 UTC
#### Description:

Summary Reports are a type of reporting requirement specific to the IA stream
Usually, a payment is attached to it, as a percentage of the total budget

Logic and or fields associated to this report need to be confirmed with the business area

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by LindsayMacfarlane** [comment] 2022-11-08 18:44
PO Review (November 8, 2022):

@nanyangpro - do we have a design/wireframe for the IA Summary Page?

**Comment by nanyangpro** [comment] 2022-11-09 18:19
Hi @LindsayMacfarlane - Yes, please see in #1061. (This ticket is a duplicate of #1061, thus can be closed.)

Along with #1061, a bunch of ticket were created as outcome of Discover on IA (please see the last comment in #720). They are the issues we need to address for incorporating IA, other outdated ones can be closed as well.

**Comment by LindsayMacfarlane** [comment] 2022-11-09 19:26
Closing this ticket as per @nanyangpro recommendations.

**Closed** 2022-11-09 19:26 UTC
Labels: duplicate
