### ISSUE TITLE
Bug: submitting an empty project overview throws error [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#792] opened 2022-06-30 18:14 UTC
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in Dev (or start the app with `yarn dev --as-role CIF_ADMIN` and clean db (`make drop_db && make deploy_db_migrations`)
- click "add a project"
- try to submit without filling out any of the form fields
- receive an error

Screenshots:
https://www.loom.com/share/c4b3afb74def40579da7388a36a33371

Additional information:

**Comment by BCerki** [comment] 2022-07-07 19:59
Duplicate of https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/824, I think

**Comment by pbastia** [comment] 2022-07-20 17:16
Also duplicate of #691, closing

**Closed by pbastia** 2022-07-20 17:16 UTC
Labels: bug
