### ISSUE TITLE
Can't remove completed milestone [5]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#908] opened 2022-07-27 15:59 UTC
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- go to a project with a submitted complete milestone
- click remove
- receive error

Screenshots:
https://www.loom.com/share/07c912b8ec434d51aef809f747bd9ecb

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment] 2022-07-27 19:55
Not consistently reproducible

**Comment by dleard** [comment] 2022-11-16 19:01
closing this card. duplicate of #836

**Closed by dleard** 2022-11-16 19:01 UTC
Labels: bug, duplicate, Backlog Refinement
