### ISSUE TITLE
As a project coordinator, I want to track when & why changes were made to projects so that I can have a clear context for the projects.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#471] opened 2022-04-07 17:36 UTC
#### Description:

Sometimes a project changes scope and it's just communicated in email, would be nice to have somewhere to note this, like a comment box for projects or changes/amendments to projects.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by dleard** [comment] 2022-05-03 17:41
@elliottSlee @matthieu-foucault @LindsayMacfarlane 
Is this different from the 'reason for change' text box when editing a project? If the project changes scope, does that not mean that some data has changed? Or is this a different use case where no project data changes, but a note needs to be made somewhere?

**Comment by matthieu-foucault** [comment] 2022-05-03 17:45
This does look like a duplicate of #372

**Comment by elliottSlee** [comment] 2022-05-03 18:10
@LindsayMacfarlane this is a duplicate of #372. Can I close it?

**Comment by LindsayMacfarlane** [comment] 2022-05-03 19:14
Yes - let's close. I can do that.

**Closed** 2022-05-03 19:14 UTC
Labels: duplicate
