### ISSUE TITLE
As a project coordinator, I want to see errors when validation fails, so that I can fix them

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-cif#200] opened 2022-01-07 00:08 UTC
#### Description:

When a form is submitted (i.e. when a project revision is submitted, or if we have a multi-page form, when a "next" button is clicked), it will be validated on the client and server (see #158). The work in this user story pertains to displaying errors to the user.

Following [NNG's form design guidelines](https://www.nngroup.com/articles/errors-forms-design-guidelines/), error messages should:
 - appear next to the offending fields
 - use color *and* an icon to highlight the error message and the field

Error summaries, listing errors in a single container, may be added in a future user story

#### Acceptance Criteria:
Given that I am viewing a form
When the form has no errors
Then an empty space should be rendered below inputs, that is the same height as error messages

Given that I am viewing a form
When the form has errors after clicking on the submit button
Then errors should be displayed under the offending fields, in red (#a12622), preceded by a warning triangle icon

#### Development Checklist:
- [ ] Meets the DOD

#### Notes:
-
#### Personas:
- [Program Development Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EcVHGc4X8mhIvQHGSaGJmyAB9F1iBe7MSH1Y1fBKUc1skA?e=fzATIc)
- [Operations Team](https://bcgov.sharepoint.com/:b:/t/00608-CIFInternalUsers/EaswKcprmuNKpEuY29a-Os0BG-h5u-Ztou7UuzK3x0xfjw?e=e8oR1i)

**Comment by matthieu-foucault** [comment] 2022-01-20 21:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/200?planning-poker) with ZenHub @AlexZorkin @dleard @pbastia

**Comment by LindsayMacfarlane** [comment] 2022-02-25 00:36
@matthieu-foucault @AlexZorkin 

Alex indicates that it might be easier to start this ticket with a fresh pull from develop. With all the changes to the repo, form structure and Alex's limited time on the project, it has been hard to keep up with all the changes necessary to implement this ticket. Matthieu - how would you like to proceed on this one?

**Comment by matthieu-foucault** [comment] 2022-02-25 00:41
I'd remove Alex's assignment and put this issue back in the sprint backlog and we can find some other issues more adapted to Alex's availability

**Comment by LindsayMacfarlane** [comment] 2022-03-03 22:40
I think I'm testing too early - still looks like the old error messages :)

**Comment by dleard** [comment] 2022-03-04 00:04
The deploy got stuck on a happo screenshot CI failure. I've deployed it to dev now and it's ready to look at.
If you enter a '1' in the rfp number field and then click submit you can see a custom error message specific to that format (should be 3-4 digits)

**Comment by LindsayMacfarlane** [comment] 2022-03-04 00:09
Sweet. Thanks @dleard! Overall looks fantastic. Project Status doesn't seem to have an error message - should it?

**Comment by dleard** [comment] 2022-03-04 00:11
Project status is not marked as a 'required' field, so there should be no validation error for that field. Whether it should be required is a different discussion.

**Comment by LindsayMacfarlane** [comment] 2022-03-04 00:13
Thanks! That could be a good usability testing question. 

Perhaps a bug - i noticed that the operator code wasn't completing?

**Comment by dleard** [comment] 2022-03-04 00:17
The (null) operator code beside some of the operators is because they are the operators that have been automatically imported from swrs. These operators will not have an operator code by default as operator codes are not swrs data. A CIF user will have to enter codes for imported operators. We shouldn't have the (null) show up though, it should just be blank, but that's not so much a bug as a UI improvement.

**Comment by matthieu-foucault** [comment] 2022-03-04 16:14
We might want to add an error message here, asking the user to set a code for the selected operator.

**Comment by dleard** [comment] 2022-03-04 17:58
on further inspection, it's the bcRegistryId that is shown alongside the operator name in the dropdown, not the operator code. But the issue is the same. Should we create a card for showing an error if the bcRegistryId is null for an operator? (good first issue?)

**Comment by matthieu-foucault** [comment] 2022-03-04 18:01
I am wondering if this operator selector needs to be that complicated. It's showing the operator legal name, BC registry ID and trade name all in one component, which may be too much. Our analysis of the spreadsheet used by the CIF team shows that they're only using the legal name.

The BC registry ID being null shouldn't be an issue though.

**Comment by dleard** [comment] 2022-03-04 18:02
actually, I guess it's both. The order of the forms confused me, the operator code is used in the RFP number above and the bcRegistryId in the dropdown

**Comment by dleard** [comment] 2022-03-04 18:02
We could remove the bcRegistryId from the dropdown display then and show an error if the operator code is null

**Comment by matthieu-foucault** [comment] 2022-03-04 18:04
I think that the trade name might be overkill too, we may want to ask our users about that though, or wait for user testing to be conducted

**Comment by dleard** [comment] 2022-03-04 18:07
I'll start a card for removing the registry number, adding the operator code and an error if the code is not defined. We can leave the trade name to be done separately pending user testing.

**Comment by dleard** [comment] 2022-03-04 19:08
I've added a card for this: #320

**Closed** 2022-03-04 19:36 UTC
Labels: User Story
