### ISSUE TITLE
Report statuses in tasklist are incorrect [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#802] opened 2022-07-05 16:14 UTC
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in dev
- create a project
- click to add a quarterly report (or annual report) but don't fill out anything in the form
- navigate away and note that the report status changes to "filled"
- navigate back and see the status is still "filled" but there are validation errors

Screenshots:
https://www.loom.com/share/3396cbb076a4450192c0a55323eff38b

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by pbastia** [comment] 2022-07-07 21:30
Closed, duplicate of #614

**Closed by pbastia** 2022-07-07 21:30 UTC
Labels: bug
