### ISSUE TITLE
As a CIF administrator, I want to see whose action an amendment is waiting for, so I know who to notify

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#1166] opened 2022-11-08 00:07 UTC
#### Description:

This is part 1 of #982
It includes the form element with the dropdown, and an inactive button

[Prototype Example 1 (Notify Tech Team)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A8493&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A8493&show-proto-sidebar=1)
[Prototype Example 2 (Notify Director)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7927&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7927&show-proto-sidebar=1) 
[Prototype Example 3 (Notify Proponent)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF-Design?page-id=3989%3A5985&node-id=3989%3A7085&viewport=-674%2C-451%2C0.24&scaling=scale-down&starting-point-node-id=3989%3A7085&show-proto-sidebar=1)

#### Acceptance Criteria:

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can see a "Pending actions from" header 

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can select the notification recipient I require from a dropdown
And the list of recipients available is one of: Ops Team, Tech Team, Director, Proponent

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
And I change the notification recipient
Then the notification recipient is saved (= persisted on refresh)

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can see a "Notify" button
And clicking this button is not effective (to be addressed in #1167)

#### Development Checklist:

- [x] new form element for the control
- ~[ ] update the project revision record when the field changes~
- [x] initially, the multiple values for that field can be hardcoded in the form schema as an `anyOf`

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [x] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by Dianadec** [comment] 2022-11-08 18:23
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1166?planning-poker) with Zenhub @pbastia @Sepehr-Sobhani @gurjmatharu @sam-warren @tmastrom @mikevespi @BCerki

**Comment by pbastia** [comment] 2022-11-08 18:29
@nanyangpro Flagging you on this card instead - it's the same comment as on #982. 
Based on this prototype, updating the status won't save until the user clicks the "Save" button - but updating the "pending actions from" field will save immediately. Is there a reason for the different behaviour?

**Comment by nanyangpro** [comment] 2022-11-09 18:57
Great question, @pbastia - This is actually a thing I would appreciate your insights. Ideally both fields should have the same behaviour.

Is it possible that we have 2 buttons next to the "Pending actions from"?
- One labelled as "Update" for confirming the change (same as the one for "Status" in the prototype)
- The other labelled as "Notify" for the emailing #1167

**Comment by LindsayMacfarlane** [comment] 2022-11-21 21:44
Hi @pbastia @nanyangpro - was Nan's previous comment addressed?

**Comment by Dianadec** [comment] 2022-11-22 16:53
@BCerki we need your estimate :)

**Comment by pbastia** [comment] 2022-11-22 18:47
@nanyangpro given that all the other forms have a "save-on-change" feature - should we consider this approach here to, and not have these buttons? this way the field's representation always matches the state of the sytem, and we keep consistency with the rest of the app

**Comment by nanyangpro** [comment] 2022-11-26 00:00
@pbastia - "save-on-change" were NOT the approach we agreed with the CIF team. Instead, for all the routinely updated fields, we want the user to confirm the change by clicking the "Update" button next to it. (Please see example prototypes in #1158) Thus for consistency, I would lean on having the "Update" button for this fields still. Happy to discuss if you like.

**Comment by gurjmatharu** [comment] 2022-11-28 21:30
@nanyangpro is the field `pending_changes_from` optional?  If so what is the default value of the field.

Please confirm that the following:
 Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
And I change the notification recipient
Then the notification recipient is saved (= persisted on refresh)
is not apart of the AC?

**Comment by nanyangpro** [comment] 2022-11-29 18:28
Thanks for confirming, @gurjmatharu. 

- Yes, optional. Ops Team.
- Correct. The field is saved upon clicking on the "Update" button next to it (consistent with other Routinely Updated Fields).

**Comment by nanyangpro** [comment] 2022-12-02 20:47
Hi @pbastia - As discussed with @gurjmatharu, @Sepehr-Sobhani, @BCerki, we would need your help to achieve an agreement on if we want to add the "Update" button next to the "Pending actions from" field (please see my previous two comments). If so, we'll need to create a new user story for it since it's out of scope of this ticket. I'll book us a meeting for when you are back on Monday.

**Comment by pbastia** [comment] 2022-12-05 18:44
As discussed, after a short design discussion w
- No update button will be shown as part of this PR. Changing the notification recipient field persists the change in the backend right away (ie a custom mutation that creates a new revision, with no form changes, and commits that revision)
- @gurjmatharu and @Sepehr-Sobhani will pair on that custom mutation, which will be required in #981 too
- @nanyangpro will update the designs of the "Routinely updated fields" to reflect the discussion
- A card will be created to refactor this page to use that "Routinely updated fields" design pattern once the designs have been refined.

**Comment by pbastia** [comment] 2022-12-05 22:27
@nanyangpro confirming that this feature won't be available for amendments that have been approved already

**Comment by nanyangpro** [comment] 2022-12-09 17:21
Hi @pbastia, confirmed.

Quick question, are we allowing the status of a revision record being changed backwards once applied/approved?

**Comment by pbastia** [comment] 2022-12-09 17:36
@nanyangpro no, any changes that need to be made on an approved revision requires creating a new revision and make those changes there

**Comment by nanyangpro** [comment] 2022-12-09 18:07
Great. Thanks for confirming, @pbastia!

**Comment by LindsayMacfarlane** [comment] 2022-12-13 23:07
Hi @gurjmatharu Thanks! A quick clarifying question given there seems to have been a lot of discussion between the team...I only see 1 of the 4 acceptance criteria completed as part of this ticket. Is that correct? I see the notify button was removed as part of this ticket, but the others? Thanks for any and all insight!

Given I am a CIF administrator
When I am viewing a single amendment from the revisions table
Then I can see a "Pending actions from" header

cc: @pbastia and @nanyangpro for your input.

**Comment by gurjmatharu** [comment] 2022-12-14 18:16
@LindsayMacfarlane please take a look here https://www.loom.com/share/1ada258eb0944811acf3817bd3f25dd0 let me know if there are any issues/questions

**Comment by LindsayMacfarlane** [comment] 2022-12-14 18:28
That was super helpful @gurjmatharu ! Thank you!

One observation: the order of the pending actions from dropdown list. @nanyangpro, can you confirm if there was a particular order needed? This can be addressed in a future ticket if required.

**Comment by nanyangpro** [comment] 2022-12-15 03:17
Thanks for confirming, @LindsayMacfarlane! No particular order is needed for the "Pending actions from" dropdown list, but ideally the same as the prototype: Ops Team, Tech Team, Director, Proponent.

**Comment by pbastia** [comment] 2022-12-20 18:13
@Sepehr-Sobhani re: [your comment](https://github.com/bcgov/cas-cif/pull/1233#issuecomment-1344929231) I would leave the AC of this card as they are, and make that a new card.
We'll need @nanyangpro and @suhafa to confirm the workflow of committing a revision when we change this status

**Comment by Sepehr-Sobhani** [comment] 2022-12-20 18:36
> @Sepehr-Sobhani re: [your comment](https://github.com/bcgov/cas-cif/pull/1233#issuecomment-1344929231) I would leave the AC of this card as they are, and make that a new card. We'll need @nanyangpro and @suhafa to confirm the workflow of committing a revision when we change this status

@pbastia @nanyangpro @suhafa Card created here: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1293

**Comment by nanyangpro** [comment] 2023-01-04 19:17
I need some context regarding the workflow @pbastia mentioned. I'll drop my question in #1293, thanks for creating it, @Sepehr-Sobhani!

**Closed** 2023-01-20 16:36 UTC
Labels: User Story, High Priority
