### ISSUE TITLE
Don't show the logout alert while user is actively working in the system

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1472] opened 2023-02-28 21:48 UTC
#### Describe the task

From the observation session with (CIF) Lindsay on Feb 26, user sees the pop-up below while still actively working on the project. It's also mentioned that it has been a continuous issue for them.

![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/b2300792-c5be-4f8b-bcdb-559cbc5f3a33)

We need to test it out to confirm if this is a bug we need to resolve (see the pop-up while actively working on it), or consider extending the time from the current 30 minutes to longer period if not.

#### Acceptance Criteria

- [ ] first
- [ ] second
- [ ] third

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by pbastia** [comment] 2023-07-10 21:33
Duplicate of #1749, closing

**Closed by pbastia** 2023-07-10 21:33 UTC
Labels: Task, Backlog Refinement, Medium Priority
