### ISSUE TITLE
As an Ops Team Member, I want to select the Sector for a project, so that I can track it for a successful proponent.

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#645] opened 2022-05-24 17:41 UTC
#### Description:

CIF program staff are often requested to report out on funded projects and their relation to certain industrial sectors. 
Furthermore, an optional text input to capture a more specific "sub-sector".

A table containing the sectors (similar to `cif.report_type` table) can be made to store the accepted sectors.

Draft Figma design: https://www.figma.com/file/PzOY8RyQnVXnjZJdSv2AqQ/Wireframing_Figma?node-id=1488%3A2904

#### Acceptance Criteria:

Given I am an Ops Team member
When I am on the project overview page
Then there is a field to capture sector information

Given I am an Ops Team member 
When I am on the project overview page
And I am entering sector information
Then I am able to select the correct sector through a drop down menu

Given I am an Ops Team member 
When I am on the project overview page
Then there is an optional input field to capture additional sector information 

Given I am an Ops Team member 
When I am on the project overview page
Then I can see the fields in the same order as in the design

#### Development Checklist:
- [x] create a `cif.sector_name` table to contain the list of sectors (see next item)
- [x] sector names: Agriculture; Cement; Lime; Refining Oil & Gas; Midstream; Oil & Gas; Upstream Oil & Gas; Mining; Pulp & Paper; Utility 
- [x] add a select input to the project overview form containing the list of sectors
- [x] add an optional text input to the project overview form to capture the "additional-sector-information"
- [ ] the fields are in the same order as in the design
- [ ] Meets the DOD

#### Notes:

- During 3 Amigo's discussion, it was determined that we could hold off implementing an 'other' category until it is identified there is a need for this. Not including 'other' with a free form text field will also help maintain data quality and consistency. 
- Additional research notes from Elliott that were captured in the duplicate ticket of #560: Tech team wants to know the sector the projects are in. They like to filter projects by sector for when they receive requests for information by sector. Currently the sector is an open field in the spreadsheet, the sectors are not official sectors such as NAICS--just a list of sectors the team uses.

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included (if required)
- [x] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

**Comment by elliottSlee** [comment] 2022-05-25 17:36
duplicate of #560

**Comment by LindsayMacfarlane** [comment] 2022-05-31 19:41
@nanyangpro @pbastia - should this user story go back to being about the sector as that is the only related acceptance criteria?

**Comment by nanyangpro** [comment] 2022-05-31 19:53
Good point @LindsayMacfarlane. I had a similar question and wanted to confirm during our 3 amigos meeting tmr with @pbastia.
Is there a reason to keep this ticket separate from #642?

**Comment by pbastia** [comment] 2022-05-31 20:18
#642 is related specifically to project budgeting, and we might want to have this in a separate form (TBD at the 3 amigos meeting), this one is just a regular addition to the project overview form, I kept them separate so that one doesn't block the other

@LindsayMacfarlane I changed the title back but github is being confusing about what the current title is

**Comment by nanyangpro** [comment] 2022-05-31 20:23
Gotcha, thanks @pbastia!

**Comment by nanyangpro** [comment] 2022-06-01 23:10
@pbastia, @LindsayMacfarlane  - The wireframe for #645 has been updated based on the 3 amigos discussion, feel free to update the ticket accordingly and ask any questions you may have.

**Comment by pbastia** [comment] 2022-06-07 17:34
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/645?planning-poker) with ZenHub @BCerki @dleard @gurjmatharu @matthieu-foucault @mikevespi @Sepehr-Sobhani

**Comment by LindsayMacfarlane** [comment] 2022-06-22 22:49
Thank you @dleard. Looks great. I tested in dev by:
1. Creating a new project
2. Editing an existing project

Meets acceptance criteria.

**Closed** 2022-06-22 22:49 UTC
Labels: User Story, High Priority
