### ISSUE TITLE
Primary contact form huge error text [5]

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#735] opened 2022-06-14 19:19 UTC
Describe the Bug:
The primary contact form on the Project contact form shows a huge error text when hitting submit button without choosing any contact on the primary contact form.
Notes: 
1 - This issue doesn't exist on the secondary contact form
2 - This issue doesn't exist when we have a secondary contact form

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
Click the create new project button from the dashboard or try to edit an existing project -> go to the project contacts form and hit submit without choosing any primary contact or adding a secondary contact form

Screenshots:
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/6243a3ea8726850c1675becd/6a264864-aa22-44dc-a1e2-3bb6803843fd)

**Comment by LindsayMacfarlane** [comment] 2022-07-07 21:47
Thanks @BCerki - I'm probably testing before this got merged to dev? I can still reproduce the error:
![image.png](https://images.zenhubusercontent.com/60f9db089e3a388facde96d1/2ad2ee80-f44c-456c-8595-3df8964e5025)

**Comment by LindsayMacfarlane** [comment] 2022-07-13 17:21
Thank you @BCerki - I could not reproduce the bug :)

**Closed** 2022-07-13 17:21 UTC
Labels: bug
