### ISSUE TITLE
Bug: Complete date label on quarterly report displays the wrong date [3]

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-cif#865] opened 2022-07-18 20:55 UTC
Describe the Bug:

Adding a quarterly report due on May 5 and received on May 9, 2022 resulted in May 10 displayed as the completed date

Probability (how likely the bug is to happen, scored from 1-5): 1
Quarterly reports are usually entered on a project

Effect (how bad the bug is when it does happen, scored from 1-5): 2
Could lead to mistakes when assessing whether a report is on time or not

Steps to reproduce the behaviour:

Screenshots:
Taken at 1:53pm PST on  a CIF team member's computer (test environment)
![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/ed6ab760-b7fd-4134-a417-3309b61b13a6
)

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment] 2022-07-22 23:41
I tried to reproduce it but couldn't. here is the screenshot was taken at 4:37 PST on my dev environment:
![Screen Shot 2022-07-22 at 4 39 10 PM](https://user-images.githubusercontent.com/52381975/180580972-5fe049cb-9f9e-4363-837a-26620f2e7d04.png)

**Comment by BCerki** [comment] 2022-07-27 14:34
I can still reproduce it: 
![image](https://user-images.githubusercontent.com/77306764/181274694-c0d3b718-f598-4734-ba63-ac3c6f1b92ca.png)

**Comment by BCerki** [comment] 2022-07-27 18:56
This bug appears to only happen to users in non-PST/PDT timezones. Times are set to 23:59:59, so if a user is in mountain time or anywhere farther east, the time becomes the next day. (Check with Amanda re her location during the user testing session.)
This is likely caused by the casting in `form_change_as_reporting_requirement.sql`: `(new_form_data->>'submittedDate')::timestamptz as submitted_date`.
It's unlikely that people will use the app from outside PST/PDT so lowering priority.

**Comment by LindsayMacfarlane** [comment] 2022-08-05 22:37
Thank you @BCerki - I couldn't reproduce, but I'm unclear if that is because of your comment above or because the bug was solved :)

**Comment by BCerki** [comment] 2022-08-08 17:01
I can't reproduce it over here either

**Comment by pbastia** [comment] 2022-08-08 17:08
It's still showing in -test for me, I can hop on a call to show you if it helps

**Comment by LindsayMacfarlane** [comment] 2022-08-10 17:31
Checking in on the status of this ticket @BCerki @pbastia. Pierre, wouldn't you have been able to reproduce the error in test since we hadn't pushed the fix there yet?

**Comment by BCerki** [comment] 2022-08-15 18:24
@LindsayMacfarlane, that's correct, the fix isn't in test yet

**Comment by LindsayMacfarlane** [comment] 2022-08-15 18:26
Thanks @BCerki !

**Closed** 2022-08-31 22:16 UTC
Labels: bug
