### ISSUE TITLE
Usability testing of quarterly report forms

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#408] opened 2022-03-22 22:34 UTC
#### Describe the task

Complete user testing of quarterly report to validate functionality. 

#### Acceptance Criteria

- [x] create task(s) & write script
- [x] identify users from ops team to test wireframe
- [x] schedule testing session(s)
- [x] ask devs to push quarterly reports to prod
- [x] create mock data (if necessary)
- [x] conduct session(s)
- [x] document feedback
- [x] create user stories based upon feedback

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by elliottSlee** [comment] 2022-03-29 17:24
dupe of #410

**Comment by elliottSlee** [comment] 2022-05-25 15:34
These sessions were with conducted with [Bailey](https://bcgov.sharepoint.com/:v:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Usability%20Testing%20%26%20Discovery%20Recordings/Quarterly%20Report%20Test%20and%20Budget%20Wireframe%20Walkthrough%20with%20Bailey_24May22.mp4?csf=1&web=1&e=ypb1nn) and [Amanda](https://bcgov.sharepoint.com/:v:/r/teams/00608-ScrumTeam/Shared%20Documents/Scrum%20Team/CIF/Usability%20Testing%20%26%20Discovery%20Recordings/Quarterly%20Report%20Test%20and%20Budget%20Wireframe%20Walkthrough%20with%20Amanda_24May22.mp4?csf=1&web=1&e=drFG1X).

**Comment by LindsayMacfarlane** [comment] 2022-05-25 16:14
Thank you @elliottSlee !

**Closed** 2022-05-25 16:14 UTC
Labels: Task, Backlog Refinement, UX Design
