### ISSUE TITLE
Correct display of the "Payment Percentage of Performance Milestone Amount"

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/cas-cif#1477] opened 2023-02-28 23:56 UTC
#### Describe the task

On the Emissions Intensity Report page, the "Payment Percentage of Performance Milestone Amount" field should display a percentage between 0% and 100%. (The proponent can never be paid more than 100% of the payment even if they exceed 100% GHG performance. They also can never owe money if their percentage is less than 0%.)

![image.png](https://images.zenhubusercontent.com/5e3b4990c0f4cb9e2c9b1b1e/18a75be6-957f-4160-b48d-1c2403536664)

#### Acceptance Criteria

- [ ] If the calculated value goes over 100%, display 100%. If the calculated value goes negative, display 0%. (rework `cif.form_change_payment_percentage` computed column` to cap amounts)

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by BCerki** [comment] 2023-03-21 17:16
This looks like a duplicate of https://github.com/bcgov/cas-cif/issues/1478. @LindsayMacfarlane, it looks like you thought the same thing and then removed the `duplicate` label--what's different about this one?

**Comment by nanyangpro** [comment] 2023-04-04 17:27
Thanks for confirming, @BCerki (cc: @pbastia) - I believe it's the exact same thing as #1478. Feel free to close it!

**Comment by nanyangpro** [comment] 2023-04-04 17:33
Close as confirmed duplication with Brianna.

**Closed** 2023-04-04 17:33 UTC
Labels: Task, Backlog Refinement, Needs AC, High Priority
