### ISSUE TITLE
Project revisions/amendments committing workflow based on the revision status

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1293] opened 2022-12-20 18:35 UTC
#### Description:

We'll need @nanyangpro and @suhafa to confirm the workflow of committing a revision when we change this status. some context around this card:
- https://github.com/bcgov/cas-cif/issues/1166#issuecomment-1359945669
- https://github.com/bcgov/cas-cif/pull/1233#issuecomment-1344929231

- Ptototype: [Edit Revision - Change "Status" (generic)](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=7283-870&viewport=-470%2C1174%2C0.2&scaling=scale-down&starting-point-node-id=7283%3A870&show-proto-sidebar=1)
- Prototype: [Edit Revision - Commit changes](https://www.figma.com/proto/PzOY8RyQnVXnjZJdSv2AqQ/CIF---Internal-User-Portal?page-id=2289%3A2663&node-id=7835-1111&viewport=-470%2C1174%2C0.2&scaling=scale-down&starting-point-node-id=7835%3A1111&show-proto-sidebar=1)

#### Acceptance Criteria:

Given I am a CIF administrator
When I am on the Amendments & Other Revisions form
Then I can select the status I require from a dropdown

Given I am a CIF administrator
When I change the status to either `Approved` or `Applied`
Then the revision is committed and no more changes are allowed to the revision, and the "View/Edit" button in the table changes into "View" only

Given I am a CIF administrator
When I change the status to either `Approved` or `Applied`
Then I see a read-only page and one more `Revision record history` at the bottom of the page

Given I am a CIF administrator
When I am on the Amendments & Other Revisions form
Then I can update the optional general comments field if the status is not `Approved` or `Applied`

#### Development Checklist:

- [x] Create a new SQL function to update or commit a revision based on the revision status OR using existing mutations (`useUpdateProjectRevision` and `useCommitProjectRevision`) based on the value of the revision status widget.
- [x] Update `RevisionStatusWidget` with the approach you decided to go
- [x] Adding tests to make sure appropriate mutation gets called when status has changed
- [x] Adding `ChangeReasonWidget` to capture the reason for a change
- [x] Tweaking `SelectWithNotifyWidget` to be aligned with wireframes
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

- As a side note: When we change the status to either `Approved` or `Applied` we shouldn't see the `update revision` button at the bottom of the page (At this time we don't have that button in place and this is just a reminder)

**Comment by pbastia** [comment] 2022-12-20 19:08
Specifically, we'll need to decide what happens when a user selects "Applied" or "Approved" status on an open project revision, and if this is an acceptable way of committing a project revision

**Comment by BCerki** [comment] 2022-12-20 19:08
This card may affect this issue as well: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1284

**Comment by nanyangpro** [comment] 2023-01-04 19:38
Changing the "Status" of a Revision Record to "Approved" for Amendments or "Applied" for General/Minor Revisions is when the changes should be committed to the database and reflected on other front-end forms. We need additional ux designs to make sure the user is aware of the differences/impacts before and after taking the action.

**Comment by Dianadec** [comment] 2023-02-07 20:14
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Climate-Action-Secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1293?planning-poker) with Zenhub @dleard

**Comment by LindsayMacfarlane** [comment] 2023-02-22 20:02
Backlog refinement (Feb 22, 2022): There are still a lot of outstanding questions to support moving forward with amendments and revisions. Taking a pause to do a more in-depth review/whiteboarding session before continuing with the implementation of this EPIC.

**Comment by pbastia** [comment] 2023-03-14 23:58
@nanyangpro @suhafa is there a wireframe for this?

**Comment by nanyangpro** [comment] 2023-03-28 23:39
Hi @Sepehr-Sobhani - I've added a link to the design in the description. Additionally, would you mind refining the second set of the AC into:

> Given I am a CIF administrator
When I change the status to either `Approved` or `Applied`
Then the revision is committed and no more changes are allowed to the revision, and the "View/Edit" button in the table changes into "View" only

?

**Comment by Sepehr-Sobhani** [comment] 2023-04-17 23:59
Since revisions/amendments change reason got part of the changes on this issue, I've updated the AC to capture the work.

**Comment by pbastia** [comment] 2023-04-26 21:00
Thank you @Sepehr-Sobhani ! Feature works as intended

**Closed** 2023-05-23 22:53 UTC
Labels: User Story, High Priority, Giraffe 🦒
