### ISSUE TITLE
User testing of milestone report prototype

### ISSUE THREAD

**Issue by LindsayMacfarlane** [bcgov/cas-cif#404] opened 2022-03-22 22:13 UTC
#### Describe the task

Take prototype out to ops team for testing, review and input. 

#### Acceptance Criteria

- [x] identify users from ops team to test wireframe
- [x] schedule testing session(s)
- [x] prepare script for test
- [x] get script approved by team
- [x] conduct session(s)

#### Additional context

- Note: depending on volume of feedback, updating wireframe could be pulled into its own ticket.

**Comment by elliottSlee** [comment] 2022-03-29 17:22
dupe of #407, #408, #410

**Comment by LindsayMacfarlane** [comment] 2022-03-29 17:34
@elliottSlee - Let's confirm with Suha before closing this ticket. We will created this ticket based on some next steps.

**Comment by LindsayMacfarlane** [comment] 2022-03-29 18:16
re-opening to re-edit.

**Comment by LindsayMacfarlane** [comment] 2022-03-29 21:40
@suha - please feel free to edit and update as you see fit. This ticket now captures the testing of the prototype related to milestone reports.

**Comment by suhafa** [comment] 2022-04-13 17:07
We've one more session today, but I'd consider this ticket done.

**Closed by suhafa** 2022-04-13 17:07 UTC
Labels: Task, UX Design
