### ISSUE TITLE
As a project coordinator, I want to know that when I press the add contacts to a project button it will add more contacts, not commit the data so that I can be confident I will remain on the page.

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/cas-cif#461] opened 2022-04-07 14:47 UTC
#### Description:

In the create project page, the button for add another contact currently says "Add" and is a primary button which normally "drive users to the next positive action such as going to the next page, completing an action, or starting a user journey." Usability testing revealed that people thought the button would submit the contacts data to the database, not add another contact. Perhaps this could be changed to a secondary button that says "Add another contact."

#### Acceptance Criteria:

Given that a user is on the add a contact to a project page
When they want to add another contact to a project
Then they will look to a button that they recognize will do that

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

#### Notes:

-

**Comment by pbastia** [comment] 2022-05-17 17:42
@elliottSlee just to confirm, is this about the ambiguity caused by having the "Add" and the "Submit" button side by side, with semantically close meanings?

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/66202d82-d961-47e3-b0e3-2271d2793fc8)

**Comment by elliottSlee** [comment] 2022-05-17 18:17
@pbastia Yes, users felt that Add meant Submit.

**Comment by suhafa** [comment] 2022-05-30 20:25
@pbastia - Could we change 'Add' to 'Add another contact' I think wording alone can tackle this c:

**Comment by pbastia** [comment] 2022-05-30 21:21
Sounds good to me 👌

**Comment by suhafa** [comment] 2022-06-03 21:27
<img width="566" alt="image" src="https://user-images.githubusercontent.com/99216375/171955289-8eb234e4-23de-4126-bdb7-15592e21dc94.png">
New UI to make the distinction clear. Changed text of secondary contacts button to say ‘Add a secondary contact’ with + sign. Secondary contacts button has secondary button design instead.

**Comment by LindsayMacfarlane** [comment] 2022-06-07 17:02
This issue is no longer required as it has been addressed through #694, #695, #701 and #705.

**Comment by LindsayMacfarlane** [comment] 2022-06-07 22:12
Closing ticket.

**Closed** 2022-06-07 22:12 UTC
Labels: duplicate
