### ISSUE TITLE
Set up crunchy monitoring for CIF Prod

### ISSUE THREAD

**Issue by dleard** [bcgov/cas-cif#1104] opened 2022-09-23 23:00 UTC
Crunchy monitoring was set up before we had a prod db instance. We should configure crunchy monitoring to monitor the production instance. This can be done easily from within our pipeline repo by updating the .crunchy_values file and running `make install_crunchy_monitoring`.
(Matthieu and I could also be removed from the alert list at the same time)

**Comment by pbastia** [comment] 2022-11-16 19:04
duplicate of #1102

**Closed by pbastia** 2022-11-16 19:04 UTC
Labels: Tech Debt, High Priority
