### ISSUE TITLE
Goals for External User Research

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-cif#210] opened 2022-01-11 18:41 UTC
To prepare for external user research (when we have capacity & approved PIA), this ticket documents outlining our goals for the research to set expectations.

- [ ] Ideate potential areas of focus
- [ ] Ideate potential methods of research & testing
- [ ] Outline high-level goals for completing external user research
- [ ] Document this in the Scrum Team channel for future reference

**Comment by elliottSlee** [comment] 2022-03-07 16:11
Duplicate of #211

**Closed** 2022-03-15 17:46 UTC
Labels: duplicate
