### ISSUE TITLE
As a CIF user, I want to see the differences on project overview calculated fields since the last revision, so that I can focus on what did change

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-cif#1231] opened 2022-12-01 22:40 UTC
#### Description:

Calculated fields are handled by computed columns, which our current diff logic can't display. For example, diff for calculated gross, net and holdback amounts for a milestone isn't shown on the summary page (page with red/black strikeout). This is likely because the calculated values are not actually part of the schema. 

This card is about implementing diffs for the Project Overview form. The calculated values on the overview form are:
- Rank

Note: this Issue is about showing the difference between the values a user has just typed into a form and the values in the previous form change. Pulling in the third diff of latest committed revision is [a separate card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1569).

#### Acceptance Criteria:

Given I have added enough values to complete the calculation for the first time
When I view the summary page
Then the diff displays the newly calculated value

Given I have changed values that affect the calculated value
When I view the summary page
Then the diff displays changed values properly for calculated values

Given I have removed enough values to prevent the calculation
When I view the summary page
Then the diff displays removed calculated values properly

#### Development Checklist:
- [x] Any front-end calculated values are refactored into computed_columns:
- - [x] n/a for overview form
-  [x] Refactor calculations that are on `project_revision` to be on `form_change` instead (this will also make the calculation dynamic)
- - [x] project_revision_rank
- [x] Query the previously calculated values under `formChangeByPreviousFormChangeId`
- [x] Pass the previously calculated value to `CustomDiffFields` via `formContext.oldData`
- [x] Pass the current calculated value to `CustomDiffFields`. Multiple ways to do this: synthetically update the value on the summary page before passing, in `CustomDiffFields` grab the values out of `formContext`, etc.

- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [na] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment] 2023-01-17 18:36
@dleard @BCerki this might be fixed with the latest round of bug fixes

**Comment by dleard** [comment] 2023-01-19 19:41
@pbastia This is still needed. I'll flesh out this card

**Comment by LindsayMacfarlane** [comment] 2023-01-24 19:50
Question: ticket is labelled as a bug. but written as a user story?

**Comment by pbastia** [comment] 2023-01-25 17:18
I'd say it can be either, depending on how you look at it, a bug or a missing feature. Converting the type since that's how we wrote it :)

**Comment by BCerki** [comment] 2023-03-22 17:05
This might be addressed by implementing wild wild west

**Comment by pbastia** [comment] 2023-04-18 18:10
Developers: Figure out what the impact of this card would be on the multiple forms, and assess how much refactoring this would mean to achieve this functionality.

Idea:
- summary forms would calculate values (or use the stored, computed values in the form_change where applicable) for both the current revision, and the latest committed revision

**Comment by BCerki** [comment] 2023-04-19 22:33
I ~*think any of the calculations using `project_revision` instead of `form_change` won't dynamically update

**Comment by nanyangpro** [comment] 2023-04-25 18:03
Backlog refinement Apr 25: the team suggests @pbastia continuing estimating tickets.

**Comment by nanyangpro** [comment] 2023-04-25 18:08
Backlog refinement Apr 25: #1231, #1614, #1616, and #1619 should share similar patterns, so should be easier to implement once we finish the first ticket. This one was suggested by @BCerki to be the first one to tackle since it's easiest, and rest should be estimated accordingly.

**Comment by pbastia** [comment] 2023-05-10 23:47
@BCerki thank you for the hard work!
When removing the score value, the summary page displays an empty string for the rank, instead of "REMOVED". Is this the intended behaviour?

![image.png](https://images.zenhubusercontent.com/5faafee70e671ac198e88bc7/3d25af40-8e3c-4ddc-8bfe-29c7c73fa3d2)

**Comment by pbastia** [comment] 2023-05-16 00:04
I can see the diff on the Rank calculated field. Nice work @BCerki !

**Closed** 2023-05-23 22:53 UTC
Labels: User Story, Giraffe 🦒
