### ISSUE TITLE
Wrong user error message after clearing report due date [4]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-cif#797] opened 2022-07-05 14:41 UTC
Describe the Bug:

Probability (how likely the bug is to happen, scored from 1-5): 2
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 2
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
- in Dev
- create a report and enter a due date
- clear the due date
- try to submit the form
- receive error that the input should be a string rather than the message about entering a value

Screenshots:
https://www.loom.com/share/e30de8d7794d47759b307a072559e826
Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment] 2022-07-21 20:29
@BCerki I couldn't reproduce the bug. I think that is addressed with https://github.com/bcgov/cas-cif/pull/884
May I close this issue?!

**Comment by Sepehr-Sobhani** [comment] 2022-07-21 23:00
Addressed in #884.

**Closed by Sepehr-Sobhani** 2022-07-21 23:00 UTC
Labels: bug
